version: '3.8'
services:
  postgres_db:
    image: postgres
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_DB=amulet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
